import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import React from "react";

const poppins = localFont({
  src: "./fonts/poppins-v21-latin-regular.woff2",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Raven Justin Garcia | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  contact_info,
  main,
}: Readonly<{
  contact_info: React.ReactNode;
  main: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased `}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          <div className="mx-auto max-w-screen-lg pt-[150px]">
            <div className="flex w-full justify-center gap-6 my-4">
              {contact_info}
              {main}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
