import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import React from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  contact_info,
  main,
}: Readonly<{
  children: React.ReactNode;
  contact_info: React.ReactNode;
  main: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <div className="max-w-screen-lg mx-auto pt-40">
            <div className="flex justify-center space-x-4 w-full">
              {contact_info}
              {main}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
